version: "3.7"

services:
  traefik:
    image: traefik:${VERSION:-v1.7.21-alpine}
    ports:
      - target: 80 # http://bit.ly/2SfiOhk
        published: 80
        protocol: tcp
        mode: host
    command:
      # - --debug
      # - --loglevel=INFO
      - --entryPoints=Name:http Address::80 Compress:true
      - --defaultEntryPoints=http
      - --docker.swarmmode=true
      - --docker.exposedbydefault=true
      - --docker.network=traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: ${MODE:-replicated}
      # placement:
        # constraints: [node.role==manager]

networks:
  default:
    external: true
    name: traefik-net
