global:
  smtp_smarthost: SMTP_HOST
  smtp_from: SMTP_FROM
  smtp_auth_username: SMTP_USERNAME
  smtp_auth_password: SMTP_PASSWORD

route:
  group_by: [alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: SMTP_TO
